completeing first phase of MVP testing
learn-academy-2023-india/cat-tinder-frontend-calico-aka-catmen pull request #2
Opened 2024-02-07 23:35 UTC by jayfr1122

2024-02-07 23:40 UTC, elysemontano requested changes
Let's update the Home and NotFound pages to test for more than the page rendering. It looks like both are using an image, so you can test the image has a src and an alt tag.

2024-02-07 23:55 UTC, jayfr1122 commented
thank you for the feedback, it was extremely helpful

2024-02-07 23:57 UTC, elysemontano requested changes
Great work on those updates! Just double check indentation on the Home and NotFound and you will be good to go.

2024-02-08 00:13 UTC, elysemontano approved these changes

2024-02-08 00:13 UTC, merged